markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true
  parse_block_html: true

theme: minima
title: Elementary Quantum Mechanics
description: "A fully Jekyll-powered site for Quantum Mechanics, with MathJax and GitHub Flavored Markdown."


